### ISSUE TITLE
openByUrl方法调用后没有小把手

### ISSUE THREAD

**Issue by fuiyu** [FlutterTaoBaoKe/flutter_alibc#1]
openByUrl方法调用后没有小把手，你们的框架里是不是漏了AlibcShowParams 这个参数？，以下是我的调用代码
文档中是需要这样设置back url
showParams.setBackUrl(BACK_URL);
 
`FlutterAlibc.openByUrl(
        url:link,	//必须参数
        openType : AlibcOpenType.AlibcOpenTypeAuto,
        isNeedCustomNativeFailMode : true,
        nativeFailMode :    AlibcNativeFailMode.AlibcNativeFailModeNone,
        taokeParams: taoKeParams,
        backUrl:backUrl,
      )`

**Comment by fuiyu** [comment]
已解决，谢谢作者

**Comment by qq329401134** [comment]
请问下你这个怎么解决的

**Comment by fuiyu** [comment]
> 请问下你这个怎么解决的

你的是什么问题？

**Comment by qq329401134** [comment]
跳转过去以后没有返回的那个把手

**Comment by qq329401134** [comment]
而且       openByUrl打不开我这个优惠券的页面                 "https://taoquan.taobao.com/coupon/unify_apply.htm?sellerId=2200580251937&activityId=fbcadf7fc75d413b8265e79244fcf8af",

**Comment by fuiyu** [comment]
传 backUrl，安卓可以，ios还没测试

**Comment by qq329401134** [comment]
请问下backUrl怎么传呢，我传的""，一样没有

**Comment by fuiyu** [comment]
BACK_URL（小把手）：唤端返回的scheme 
(如果不传默认将不展示小把手；如果想展示小把手，可以自己传入自定义的scheme，
或者传入百川提供的默认scheme："alisdk://")
具体看官方文档：
https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.7629140.0.0.5780be48u4A7wU&treeId=129&articleId=118203&docType=1

**Comment by qq329401134** [comment]
请问下我提供的优惠券页你openByUrl能打开吗，我打不开

**Comment by iworkcloud** [comment]
String BackUrl = '';
      if (Platform.isAndroid) {
        BackUrl = 'tbopenxxxxxxx://';
      }
