### ISSUE TITLE
IOS无法打开优惠券页面

### ISSUE THREAD

**Issue by funengqing** [FlutterTaoBaoKe/flutter_alibc#17]
今天终于能上了，原因未知,以后能不能上，未知。
这两天又看了下，之前的邮件里有参数是我弄错了，没注意看文档，直接把淘客参数写在了错误的地方。
但有现在我的代码如下（main.dart）：
FlatButton(
              child: Text("唤起淘宝，openItemDetail方式"),
              onPressed: () async {
                var result = await FlutterAlibc.openItemDetail(
                    itemID: "590722918397",
                    schemeType: AlibcSchemeType.AlibcSchemeTaoBao,
                    isNeedCustomNativeFailMode: true,
                    //淘客参数在应该在这里写
                    taokeParams: TaokeParams(
                      adzoneId: "xxxxx",
                      pid: "mm_aa_bb_xxxxx",
                      extParams: {"taokeAppkey":cccc}
                    ),
                    nativeFailMode:
                        AlibcNativeFailMode.AlibcNativeFailModeJumpH5);
                print(result);
              },
            ),
同样的参数在官方提供的demo可以打开优惠券页面。请各位亲帮我看看是哪里出了什么纰漏，itemID有可能会过期，测试的时候请替换成一个有优惠券的itemID.

**Comment by XingXiaoWu** [comment]
看不了，用新版本试试吧

**Comment by XingXiaoWu** [comment]
有问题再打开
