### ISSUE TITLE
奇怪的问题，安全初始化失败

### ISSUE THREAD

**Issue by sparksisnotspark** [FlutterTaoBaoKe/flutter_alibc#22]
新生成的项目集成flutter_alibc这个能够登陆淘宝都是ok的，然后，添加了依赖，乱七八糟的插件装一装，添加了一些本地依赖，然后就出现了 “安全初始化失败”，然后我将依赖什么的都去掉，还原成开始的时候的样子，还是会出现这个问题，安全初始化失败

**Comment by XingXiaoWu** [comment]
新生成的项目集成flutter_alibc这个能够登陆淘宝都是ok的
这不就完了。。。。

**Comment by karedem** [comment]
初始化失败请参考demo 及阿里官方文档配置

**Comment by ismanong** [comment]
你好，ErrorCode = 199；debug包可以初始化成功，release包就不可以成功，用的都是一个签名文件。之前也可以初始化成功，我感觉跟gradle版本有关。但是我试了很久，人家初始化失败都是123  我是199
后来我换了一台新电脑 配完环境就可以打release包并初始化成功。  我整个人都是问号

**Comment by sparksisnotspark** [comment]
我的问题找出来了，是minSdkVersion的问题，我将minSdkVersion改成24就出问题，如果minSdkVersion我不改就可以了，

**Comment by mimicode** [comment]
我改成 24好像依然不行
