### ISSUE TITLE
openByUrl 出现商品找不到的情况，提示”宝贝不见了“

### ISSUE THREAD

**Issue by fuiyu** [FlutterTaoBaoKe/flutter_alibc#23]
openByUrl 出现商品找不到的情况，提示”宝贝不见了“，所有商品链接直接点开是正常的，麻烦帮忙排查一下，ios和Android都出现了。
![D1B676E425A22164B6713EBA075465E7](https://user-images.githubusercontent.com/14845298/67416464-74fe5e80-f5f9-11e9-976c-70ddc9ecbe45.png)

**Comment by XingXiaoWu** [comment]
你看看用官方的demo打开你这个url是啥样

**Comment by fuiyu** [comment]
我查到原因了，貌似要指定手淘还是天猫，添加参数 
schemeType: AlibcSchemeType.AlibcSchemeTaoBao
恢复正常，之前也是正常的，这段时间突然变了。

**Comment by fuiyu** [comment]
IOS又不行了，安卓还是稳的，有遇到的朋友可以交流一下

**Comment by ismanong** [comment]
ios和android的sdk 已经更新了 版本号好像时4.0.0.9  解决的就是你这个时不时可以用，又不可以用的情况

**Comment by XingXiaoWu** [comment]
> ios和android的sdk 已经更新了 版本号好像时4.0.0.9 解决的就是你这个时不时可以用，又不可以用的情况

周末更新

**Comment by ismanong** [comment]
谢谢  13号才更新的，我今天过来看一看，哈哈没更新，提醒下

**Comment by XingXiaoWu** [comment]
更新完了

**Comment by ismanong** [comment]
谢谢
