### ISSUE TITLE
ios问题

### ISSUE THREAD

**Issue by rhymelph** [FlutterTaoBaoKe/flutter_alibc#26]
使用的版本：0.0.7
问题描述：
项目当前用到其它的插件，然后是用swfit写的，必须要在`Podfile`文件加上`use_frameworks!`
然后接入这个插件后，无法初始化，当去掉文件`POdfile`中的`use_frameworks!`正常运行，但其它插件不可用了。

**Comment by XingXiaoWu** [comment]
swift的问题有空我看看，但能否解决我不清楚，因为我只是做个桥接工作

**Comment by Slhaos7373** [comment]
楼上解决了吗？

**Comment by XingXiaoWu** [comment]
升级到0.0.13

**Comment by XingXiaoWu** [comment]
我先关闭了，有问题再打开
