### ISSUE TITLE
你好能否去掉alipaysdk.framework  这个会导致介入其他的支付宝库在pod install时候冲突

### ISSUE THREAD

**Issue by ismanong** [FlutterTaoBaoKe/flutter_alibc#28]
Installing AlipaySDK-iOS (15.5.9)
Installing Bugly (2.5.0)
Installing FMDB (2.7.5)
Installing Flutter (1.0.0)
Installing MTBBarcodeScanner (5.0.11)
Installing Reachability (3.2)
Installing tobias (0.0.1)
[!] The 'Pods-Runner' target has frameworks with conflicting names: alipaysdk.framework.

**Comment by ismanong** [comment]
tobias 这个包是专门做支付的 类似的还有一些，感觉还是把闭环交易的支付给干掉，做淘客的大部分不都是只需要授权吗？交易闭环是webview，这个是不是没那么重要呢。至于支付我们可以通过专门的包来处理。或者就是把支付也单独开放出来。就是支付宝和淘宝授权只用阿里百川的，你看可以吗

**Comment by XingXiaoWu** [comment]
这不是我需要处理的。
我只按百川文档桥接到flutter，你需要变动可以自行修改本地的依赖
