### ISSUE TITLE
IOS因为有过期的UIWebView无法通过审核，既然弃用了能否先把它屏蔽掉

### ISSUE THREAD

**Issue by qq329401134** [FlutterTaoBaoKe/flutter_alibc#29]
收到Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

这是IOS返回的通知，希望现在可以先屏蔽一下UIWebView

**Comment by XingXiaoWu** [comment]
百川自带了，参数要求uiwebview我就写了uiwebview
啥时候百川改了我才能改

**Comment by qq329401134** [comment]
哦哦  好的谢谢了，我说错了 UIWebView只会警告，不会影响审核

**Comment by jishuke** [comment]
新App上传会不能通过
