### ISSUE TITLE
登陆淘宝无法授权

### ISSUE THREAD

**Issue by funengqing** [FlutterTaoBaoKe/flutter_alibc#3]
1.已经把我自己的安全图片加入到example/ios下，点击登陆淘宝能跳到授权界面，但点击"确认授权"后就没有反应

**Comment by CaoZhen** [comment]
Android版本吧？

**Comment by XingXiaoWu** [comment]
iOS还是Android？

**Comment by XingXiaoWu** [comment]
兄弟说个话？ @funengqing

**Comment by XingXiaoWu** [comment]
已更新4.2版本，目前我们测试两端登录都正常了
建议更新，看是否还存在问题

**Comment by funengqing** [comment]
更新完后通过 ByUrl 方式打开商品，还是小把手还是无法正常返回，另外一个就是，通过ItemDetail打开商品时（有优惠券），无法跳转到优惠券页面，直接进入到详情页面，请问这个你测试的是否能正常呢？望回复，谢谢。




------------------ 原始邮件 ------------------
发件人: "吴兴"<notifications@github.com>;
发送时间: 2019年9月18日(星期三) 晚上11:35
收件人: "FlutterTaoBaoKe/flutter_alibc"<flutter_alibc@noreply.github.com>;
抄送: "看海天"<1619936543@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [FlutterTaoBaoKe/flutter_alibc] 登陆淘宝无法授权 (#3)




已更新4.2版本，目前我们测试两端登录都正常了
 建议更新，看是否还存在问题

**Comment by XingXiaoWu** [comment]
小把手是什么？
ItemDetail打开的就是详情页

**Comment by fuiyu** [comment]
新的小把手貌似要设置scheme

**Comment by XingXiaoWu** [comment]
小把手是什么？

**Comment by fuiyu** [comment]
> 小把手是什么？

一个附在边上的橙色 "返回" 按钮

**Comment by XingXiaoWu** [comment]
我在百川提供的demo中未看见此项，无法提供

**Comment by funengqing** [comment]
通过 ItemDetail 不能像官方 demo 那样吗，如果打开的是商品是有优惠券的就能通过商品的 跳到领取优惠券的页面，没有的就进入详情页




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴兴"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月19日(星期四) 中午11:47
收件人:&nbsp;"FlutterTaoBaoKe/flutter_alibc"<flutter_alibc@noreply.github.com&gt;;
抄送:&nbsp;"看海天"<1619936543@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlutterTaoBaoKe/flutter_alibc] 登陆淘宝无法授权 (#3)




小把手是什么？
 ItemDetail打开的就是详情页

**Comment by funengqing** [comment]
没有看到有可以设置 Scheme 的地方，如果有，麻烦回复告知，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fuiyu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月19日(星期四) 中午11:47
收件人:&nbsp;"FlutterTaoBaoKe/flutter_alibc"<flutter_alibc@noreply.github.com&gt;;
抄送:&nbsp;"看海天"<1619936543@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlutterTaoBaoKe/flutter_alibc] 登陆淘宝无法授权 (#3)




新的小把手貌似要设置scheme

**Comment by XingXiaoWu** [comment]
测试了一下，iOS上小把手可正常返回，请设置scheme并传入backurl参数

**Comment by XingXiaoWu** [comment]
通过ItemDetail打开商品时（有优惠券），无法跳转到优惠券页面，直接进入到详情页面

传入相关的淘宝客参数即可达成你要的效果

**Comment by funengqing** [comment]
像我这样传参数，还是无法跳到优惠券的页面如下图所示，实在找不到原因，求解。


我是在 flutter_alibc.dart 下面的 openItemDetail 方法中实例了一个 taokeParams,并且传入了adzoneId 等参数，可以看到实际上也已经返回了相对应的参数，但还是直接打开了详情页。


1.实例化 taokeParsms



2.返回的参数





PS:可不可以建立一个 QQ群或微信群让大家可以共同讨论学习。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"吴兴"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月23日(星期一) 凌晨0:23
收件人:&nbsp;"FlutterTaoBaoKe/flutter_alibc"<flutter_alibc@noreply.github.com&gt;;
抄送:&nbsp;"看海天"<1619936543@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [FlutterTaoBaoKe/flutter_alibc] 登陆淘宝无法授权 (#3)




通过ItemDetail打开商品时（有优惠券），无法跳转到优惠券页面，直接进入到详情页面
 
传入相关的淘宝客参数即可达成你要的效果
