### ISSUE TITLE
你好，可以获取授权code吗？

### ISSUE THREAD

**Issue by RoryHyman** [FlutterTaoBaoKe/flutter_alibc#32]
flutter_alibc里面渠道授权直接获取access_token，但是我只需要code就行了。。
![image](https://user-images.githubusercontent.com/37935622/70413283-fae34580-1a91-11ea-9a50-06018af9fa1f.png)

**Comment by karedem** [comment]
可以参照封装一个  截取access_token接口的部分逻辑即可
