### ISSUE TITLE
在你们的demo ios端测试  发现如果没有安装手淘，会直接跳转的手淘下载页面 ，不可以正常在h5打开页面 参数已经传了

### ISSUE THREAD

**Issue by Slhaos7373** [FlutterTaoBaoKe/flutter_alibc#4]
在你们的demo ios端测试  发现如果没有安装手淘，会直接跳转的手淘下载页面 ，不可以正常在h5打开页面 参数已经传了

**Comment by XingXiaoWu** [comment]
检查isNeedCustomNativeFailMode参数和nativeFailMode参数是否都给了
