### ISSUE TITLE
iOS ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by danieldai** [FlutterTaoBaoKe/flutter_alibc#42]
提交app到苹果 app store时遇到 如下问题：

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

我搜索了下源码，发现AliTrade中含有对UIWebView的调用

**Comment by XingXiaoWu** [comment]
请向阿里提工单
