### ISSUE TITLE
大神 能不能出个swift版本 不然很多基于swift的库不能用

### ISSUE THREAD

**Issue by niugengyun** [FlutterTaoBaoKe/flutter_alibc#44]

**Comment by a4081675** [comment]
同求。

**Comment by XingXiaoWu** [comment]
移除podfile的use_frameworks！可以用
至于别的库需要这个冲突的问题，不是我能解决的。。。

**Comment by a4081675** [comment]
> 可移除podfile的use_frameworks！可以用
> 至于别的库需要这个冲突的问题，不是我能解决的。。。

主要是好几个库冲突了。如果用swift写一套插件是不是能解决这问题了？我现在在边学边弄，好痛苦啊。

**Comment by XingXiaoWu** [comment]
> > 可移除podfile的use_frameworks！可以用
> > 至于别的库需要这个冲突的问题，不是我能解决的。。。
> 
> 主要是好几个库冲突了。如果用swift写一套插件是不是能解决这问题了？我现在在边学边弄，好痛苦啊。

就我目前的能力来看，答案是：并不能。
我只是做个桥接工作，动态库静态库的问题我暂时无能为力

**Comment by a4081675** [comment]
> > > 可移除podfile的use_frameworks！可以用
> > > 至于别的库需要这个冲突的问题，不是我能解决的。。。
> > 
> > 
> > 主要是好几个库冲突了。如果用swift写一套插件是不是能解决这问题了？我现在在边学边弄，好痛苦啊。
> 
> 就我目前的能力来看，答案是：并不能。
> 我只是做个替换工作，动态库静态库的问题我暂时无能为力

我在flutter_alibc.podspec里面添加s.static_framework = true    初始化的时候没奔溃     你看看这个有用么？

**Comment by XingXiaoWu** [comment]
那你先这么用
下次更新再加
