### ISSUE TITLE
使用taoKeLogin()的时候，安卓模拟器正常，真机留在淘宝无法返回

### ISSUE THREAD

**Issue by gap1994** [FlutterTaoBaoKe/flutter_alibc#45]
然后我试了一下用android项目测试，真机又能返回token，在flutter项目测试真机就会停留在淘宝客户端，我是用小米MIX3测试的

**Comment by XingXiaoWu** [comment]
建议debug看一下，开源的，我们没这么多真机去测试。。。

**Comment by gap1994** [comment]
后面改了打开方式就可以返回了
