### ISSUE TITLE
 在profile  use_frameworks! 后 启动就会这样子

### ISSUE THREAD

**Issue by Slhaos7373** [FlutterTaoBaoKe/flutter_alibc#49]
(
	0   CoreFoundation                      0x000000010eaa66fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000011426dac5 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010eac49b4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010eaab443 ___forwarding___ + 1443
	4   CoreFoundation                      0x000000010eaad238 _CF_forwarding_prep_0 + 120
	5   flutter_alibc                       0x0000000113cbbf1f +[AlibcTradeCommonSDK asyncInitWithSuccess:failure:] + 68
	6   flutter_alibc                       0x0000000113cd86c9 +[AlibcTradeBizSDK asyncInitWithSuccess:failure:] + 199
	7   flutter_alibc                       0x0000000113cdd92f __46-[AlibcTradeSDK asyncInitWithSuccess:failure:]_bloc<…>

**Comment by Slhaos7373** [comment]
因为项目需要用到swift插件，但是添加后闪退，能否搞下

**Comment by XingXiaoWu** [comment]
更新到0.0.13版本，不用加use_frameworks！了。直接使用即可
