### ISSUE TITLE
大佬们 4.0.0.2发布了 麻烦更新下

### ISSUE THREAD

**Issue by niugengyun** [FlutterTaoBaoKe/flutter_alibc#5]
https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.7662649.0.0.7a75be48bepQlc&treeId=129&articleId=106383&docType=1

**Comment by niugengyun** [comment]
安卓提交过PR了

**Comment by niugengyun** [comment]
@XingXiaoWu

**Comment by XingXiaoWu** [comment]
好的，晚上我们合并一下，谢谢

**Comment by niugengyun** [comment]
> 好的，晚上我们合并一下，谢谢

苹果的麻烦升级一下 谢谢

**Comment by XingXiaoWu** [comment]
好的，不过升级发布得晚些时候了，最近ss挂的厉害，推不上去，应该懂我意思。。

**Comment by niugengyun** [comment]
> 好的，不过升级发布得晚些时候了，最近ss挂的厉害，推不上去，应该懂我意思。。

懂 我的直接连不上

**Comment by XingXiaoWu** [comment]
Android已合并
iOS已更新
pub源已更新为0.0.6版本
国内镜像估计明天能得到更新
