### ISSUE TITLE
老铁，能否提升一下依赖，现在很多项目必须要高版本的flutter，我在1.12上面无法运行，谢谢

### ISSUE THREAD

**Issue by erzipl** [FlutterTaoBaoKe/flutter_alibc#51]

**Comment by niugengyun** [comment]
最新版stable没问题的

 你pod repo update一下下

**Comment by XingXiaoWu** [comment]
我本地1.17没问题，你看下是不是自己环境的问题。。。

**Comment by erzipl** [comment]
但是在使用openByUrl release版本的时候 无法拉起手淘 执行结果 1100

**Comment by erzipl** [comment]
在安卓 8.0系统

**Comment by XingXiaoWu** [comment]
这种原因去查淘宝的文档，所有错误我都是透传回来的，我也不清楚这个错误码的具体原因

**Comment by erzipl** [comment]
v1.12.13+hotfix.5 安卓端确实无法使用，您这边可以测试一下

**Comment by erzipl** [comment]
使用 flutter build apk 打包的apk无法使用 ，使用 flutter run --release又可以使用，确实不知道咋回事

**Comment by XingXiaoWu** [comment]
我们只做了一层桥接，能正常启动，就大概率不是我们的问题。
剩下的这种错误码问题，自己去查淘宝文档，我们都是透传！透传！透传！重要的话说3遍。

**Comment by erzipl** [comment]
你不能测试一下

**Comment by erzipl** [comment]
您这边的插件已经封装了几个月了，我也只是提升了一下子flutter版本，就不好用了

**Comment by XingXiaoWu** [comment]
好，请提供预期，事实，脱敏的demo，复现步骤

**Comment by erzipl** [comment]
好的  我这边整理下

**Comment by erzipl** [comment]
InkWell(
              onTap: (){
                FlutterAlibc.initAlibc();
                FlutterAlibc.openByUrl(
                  nativeFailMode: AlibcNativeFailMode.AlibcNativeFailModeJumpH5,
                  url: "https://uland.taobao.com/coupon/edetail?e=dHlsqwzuhvIE%2BdAb1JoOOp%2BxM81Ltm7nEThtHWvdMcvdTiaoS9HbDAtSKWxYFgIvkF9tcBHg12z%2BNBqE1ymy%2F6MCEagi%2FzMLlV0qxIMkztYONMba%2FYmopedth9k8bqqSHKTgBzHkoM7XTQC0vfau6E%2F9Zk7cDx8UYB1XDSZVWj7ho%2Bx34Btajnui%2Fn%2FQ7Z5VgdO5E6dhMF6z%2BEEIX1kmAg%3D%3D&traceId=0b52058815877190724897964e675d&relationId=2211619679&union_lens=lensId:0b57b768_0c95_171ab6e6b06_1ae5&xId=3mOtldh0xUoXiEnZQsfHPBFQ8yiGFDYN0KdyJc3EfYvD1h0qbMZyHX3MoPswtjwUioo5GyvLaNxNfUuUF3g299",
                  openType: AlibcOpenType.AlibcOpenTypeNative,
                  backUrl: "www",
                  isNeedCustomNativeFailMode: true,
                  schemeType: AlibcSchemeType.AlibcSchemeTaoBao,
                ).then((result){
                  debugPrint('拉起手淘商品url执行结果 ${result.errorCode}');
                } );
              },
              child:  Container(
                alignment: Alignment.center,
                  color: Colors.red,
                  width: 100.0,
                  height: 50.0,
                  child:
                  Text(
                    '点击跳转购买',
                    style: TextStyle(
                      color: Colors.white
                    ),
                  ),
              ),
            ),

**Comment by erzipl** [comment]
核心代码都在这

**Comment by erzipl** [comment]
您这边看下，我新建的一个项目依然有这个问题

**Comment by erzipl** [comment]
不管是debug 还是flutter run --release都是没有问题 就是flutter build apk以后跑不起来

**Comment by erzipl** [comment]
v1.12.13+hotfix.9 我已经把flutter版本升级到最新稳定版

**Comment by erzipl** [comment]
Error Domain=com.baichuan Code=100101 "加载身份图片失败, 请拷贝图片 (null) 至应用Main Bundle目录." UserInfo={NSLocalizedDescription=加载身份图片失败, 请拷贝图片 (null) 至应用Main Bundle目录.},安全图片一致，ios新版也是一直不能用，安全图片早已经放进去了

**Comment by erzipl** [comment]
确实比较麻烦你了，我们是很多都是半路出家，自己基本上也不大懂原生，只有用一些插件

**Comment by XingXiaoWu** [comment]
> Error Domain=com.baichuan Code=100101 "加载身份图片失败, 请拷贝图片 (null) 至应用Main Bundle目录." UserInfo={NSLocalizedDescription=加载身份图片失败, 请拷贝图片 (null) 至应用Main Bundle目录.},安全图片一致，ios新版也是一直不能用，安全图片早已经放进去了

去看淘宝文档

**Comment by erzipl** [comment]
安全图片早放进去了

**Comment by XingXiaoWu** [comment]
> 安全图片早放进去了

安全图片有改变，而你不知道改变了，你应该去看文档，而不是说安全图片早放进去了。你最好下个demo看一下安全图片变了什么

**Comment by karedem** [comment]
经测试 当前最新1.20.2 stable版本无异常  若有疑问请重新打开此iss

**Comment by xzhixian** [comment]
> 安全图片早放进去了

请问这个问题最后怎么解决的

**Comment by huoda1237** [comment]
> 但是在使用openByUrl release版本的时候 无法拉起手淘 执行结果 1100

你好，你这个问题解决了吗？我的也是在安卓上面，release环境有这个问题
