### ISSUE TITLE
flutter_alibc 0.0.13版本IOS登录问题

### ISSUE THREAD

**Issue by xq-life** [FlutterTaoBaoKe/flutter_alibc#52]
IOS端初始化成功，返回初始化code：0，但是调起淘宝登录授权，确认授权后，返回错误码：1003，返回错误信息：The operation couldn’t be completed. (AlibabaAuthSDK error 1003.)，别的打开商品那些均正常，请问我是哪里出了问题呢？

**Comment by XingXiaoWu** [comment]
> IOS端初始化成功，返回初始化code：0，但是调起淘宝登录授权，确认授权后，返回错误码：1003，返回错误信息：The operation couldn’t be completed. (AlibabaAuthSDK error 1003.)，别的打开商品那些均正常，请问我是哪里出了问题呢？

demo中是否能正常授权

**Comment by XingXiaoWu** [comment]
更到0.0.14看看吧，注意一下readme，iOS的引入加了点东西

**Comment by xq-life** [comment]
好的 感谢------------------ 原始邮件 ------------------
发件人: "吴兴"<notifications@github.com>
发送时间: 2020年5月3日(星期天) 下午4:43
收件人: "FlutterTaoBaoKe/flutter_alibc"<flutter_alibc@noreply.github.com>;
抄送: "xq-life"<1287305374@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FlutterTaoBaoKe/flutter_alibc] flutter_alibc 0.0.13版本IOS登录问题 (#52)




 
更到0.0.14看看吧，注意一下readme，iOS的引入加了点东西
 
&mdash;

**Comment by XingXiaoWu** [comment]
我测试过，可以正常登录。
你可以试试demo能不能登录。
如果还不能登录，你得去查阿里文档看看是不是哪里的配置错了

**Comment by xq-life** [comment]
好的，应该是我的环境少配置了，感谢大佬了😁------------------ 原始邮件 ------------------
发件人: "吴兴"<notifications@github.com>
发送时间: 2020年5月3日(星期天) 下午5:02
收件人: "FlutterTaoBaoKe/flutter_alibc"<flutter_alibc@noreply.github.com>;
抄送: "xq-life"<1287305374@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [FlutterTaoBaoKe/flutter_alibc] flutter_alibc 0.0.13版本IOS登录问题 (#52)




 
我测试过，可以正常登录。
 你可以试试demo能不能登录。
 如果还不能登录，你得去查阿里文档看看是不是哪里的配置错了
 
&mdash;
