### ISSUE TITLE
ITMS-90809错误被打回

### ISSUE THREAD

**Issue by as0026** [FlutterTaoBaoKe/flutter_alibc#53]
1、阿里百川iOS sdk，2020-03-24 版本号：4.0.1.0：
修复内容：UIwebview替换为WKwebview；
2、flutter_alibc为0.0.13，对应的ios V4.0.1.0 版本；

按理说插件不包含UIWebView。但是我全局查找api（grep -r UIWebView .）
Binary file ./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/mtopext.framework/mtopext matches
Binary file ./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/AlibabaAuthSDK.framework/AlibabaAuthSDK matches
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/AlibcTradeBiz.framework/Headers/AlibcURLBusContext.h:/****   辅助函数,方便后续修改UIWebView到UIWebViewProxy的情况.   ***/
Binary file ./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/WindVaneBasic matches
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVViewController.h: 如果创建了 UIWebView，此属性不生效。
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVViewController.h:@property (nonatomic, copy, nullable) BOOL (^shouldStartLoadAction)(UIView<WVWebViewProtocol> * _Nonnull, NSURLRequest * _Nonnull, UIWebViewNavigationType);
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVViewController.h:- (BOOL)webView:(UIView<WVWebViewProtocol> * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(UIWebViewNavigationType)navigationType;
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVWebViewController.h:#import "WVUIWebViewController.h"
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVWebViewController.h: * 请直接使用 WVUIWebViewController，这个类并不包含任何逻辑。
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVWebViewController.h:@interface WVWebViewController : WVUIWebViewController
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVViewControllerProtocol.h:@property (nonatomic, copy, nullable) BOOL (^shouldStartLoadAction)(UIView<WVWebViewProtocol> * _Nonnull, NSURLRequest * _Nonnull, UIWebViewNavigationType);
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVUIWebViewController+CustomizeUI.h://  WVUIWebViewController+CustomizeUI.h
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVUIWebViewController+CustomizeUI.h:#import "WVUIWebViewController.h"
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVUIWebViewController+CustomizeUI.h:@interface WVUIWebViewController (CustomizeUI)
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVWebView.h:@interface WVWebView : UIWebView <WVWebViewProtocol>
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVUIWebViewController.h: * WVUIWebViewController.h
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVUIWebViewController.h:#pragma mark - WVUIWebViewController
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WVUIWebViewController.h:@interface WVUIWebViewController : WVRuleWebViewController <WVWebViewControllerProtocol>
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WindVaneBasic.h:#import "WVUIWebViewController+CustomizeUI.h"
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneBasic.framework/Headers/WindVaneBasic.h:#import "WVUIWebViewController.h"
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/UTMini.framework/Headers/UTTracker.h://#import <UIKit/UIWebView.h>
Binary file ./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/SGMiddleTier.framework/SGMiddleTier matches
Binary file ./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/WindVaneCore matches
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/PrivateHeaders/WVCachedKey.h:// 获取 UIWebView 的内部 WebView
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/PrivateHeaders/WVCachedKey.h:// UIWebViewWebViewDelegate 类
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/PrivateHeaders/WVCommonWebView.h:@interface WVCommonWebView : NSObject <UIWebViewDelegate, WKNavigationDelegate>
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/PrivateHeaders/WVCommonWebView.h:- (BOOL)webView:(UIView<WVWebViewProtocol> *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType;
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/Headers/WVWebViewCategory.h:#pragma mark - UIWebViewCategory
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/Headers/WVWebViewCategory.h:@interface UIWebView (WVUIWebViewCategory) <WVWebViewBasicProtocol>
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/Headers/WVWKWebView.h: * WKWebView 默认的 navigationDelegate 与 UIWebView 无法兼容，因此请使用 windVaneDelegate。
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/Headers/WVNavigation.h:@property (nonatomic, assign, readonly) UIWebViewNavigationType navigationType;
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/Headers/WVWebViewDelegate.h:- (BOOL)webView:(UIView<WVWebViewProtocol> *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType;
Binary file ./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/AlipaySDK.framework/AlipaySDK matches
Binary file ./build/ios/Debug-iphonesimulator/Runner.app/Runner matches
Binary file ./build/ios/iphonesimulator/Runner.app/Runner matches

**Comment by as0026** [comment]
确认下你2020年4月15号的版本0.0.13引用的是不是最新的ios V4.0.1.0 版本？

**Comment by as0026** [comment]
./ios/.symlinks/plugins/flutter_alibc/ios/AliBaichuan/Frameworks/WindVaneCore.framework/Headers/WVWebViewCategory.h
这个类有对UIWebView的引用
/**
 * 针对 UIWebview 的 Category。
 */
@interface UIWebView (WVUIWebViewCategory) <WVWebViewBasicProtocol>

**Comment by a4081675** [comment]
好像是官方没更新这个库    只更新了AlibcTradeSDK.framework和AlibcTradeBiz.framework

**Comment by XingXiaoWu** [comment]
更到0.0.14，然后看下readme的引用，我把百川的包都移除了，直接从他们私服拉吧。
flutter_alibc我没做UIWebview,你看下能不能提

**Comment by a4081675** [comment]
> 更到0.0.14，然后看下readme的引用，我把百川的包都移除了，直接从他们
> 私服拉吧。flutter_alibc我没做UIWebview，你看下能不能提

我看了下0.0.14版本好像也不是最新的啊
s.dependency 'AlibcTradeSDK','4.0.1.0'
  s.dependency 'AliAuthSDK','1.1.0.39-bc'
  s.dependency 'mtopSDK','3.0.0.4'
  s.dependency 'securityGuard','5.4.173'
  s.dependency 'AliLinkPartnerSDK','4.0.0.24'
  s.dependency 'BCUserTrack','5.2.0.16-appkeys'
  s.dependency 'UTDID','1.1.0.16'
  s.dependency 'AlipaySDK','2.0.0-bc'
  s.dependency 'WindVane','8.5.0.46-bc7-mini'
这是你写的，应该是
s.dependency  'AlibcTradeSDK','4.0.1.5'
s.dependency  'AliAuthSDK','1.1.0.39-bc'
s.dependency  'mtopSDK','3.0.0.4'
s.dependency  'securityGuard','5.4.173'
s.dependency  'AliLinkPartnerSDK','4.0.0.24'
s.dependency  'BCUserTrack','5.2.0.16-appkeys'
s.dependency  'UTDID','1.1.0.16'
s.dependency  'WindVane','8.5.0.46-bc10'

**Comment by a4081675** [comment]
还有AlipaySDK这个需要么？

**Comment by XingXiaoWu** [comment]
![image](https://user-images.githubusercontent.com/22769131/80909791-8e792380-8d5d-11ea-841d-f96665708717.png)
他们demo这么写的，我也不知道是不是新的
https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.7629140.0.0.3ec3be481FQTH1&treeId=129&articleId=106383&docType=1

**Comment by a4081675** [comment]
好像还是需要用最新的，刚才试了下0.0.14的还是能检测出好多包含UIWebView的

**Comment by XingXiaoWu** [comment]
> 好像还是需要用最新的，刚才试了下0.0.14的还是能检测出好多包含UIWebView的

已经是最新的了啊。。。。依赖和他们放出的demo一模一样。。。

**Comment by a4081675** [comment]
![image](https://user-images.githubusercontent.com/17973196/80910208-72c34c80-8d60-11ea-8203-aca62d5e5cd8.png)
文档上面写的是这个，我先试试上传能不能通过。

**Comment by XingXiaoWu** [comment]
oh，那是我的错，我只看了demo

**Comment by a4081675** [comment]
> oh，那是我的错，我只看了demo

试了下上传还是不行，你啥时候有空换个最新的呗。

**Comment by XingXiaoWu** [comment]
> > 哦，那是我的错，我只看了demo
> 
> 试了下上传还是不行，你啥时候有空换个最新的呗。

你可以手动在你本地改一下，看看能不能上传

**Comment by XingXiaoWu** [comment]
> > 哦，那是我的错，我只看了demo
> 
> 试了下上传还是不行，你啥时候有空换个最新的呗。
你可以手动在你本地改一下，看看能不能上传

**Comment by a4081675** [comment]
> > > 哦，那是我的错，我只看了demo
> > 
> > 
> > 试了下上传还是不行，你啥时候有空换个最新的呗。
> 
> 你可以手动在你本地改一下，看看能不能上传

一开始好多库都改的面目全非了，不敢随便改本地的更新。现在已经改完更新了，等上传了。网速太慢上传一次要一个多小时。等我试完告诉你。

**Comment by a4081675** [comment]
![image](https://user-images.githubusercontent.com/17973196/80914102-13733580-8d7c-11ea-8d54-7031f1591a6f.png)
不行了，最新的里面还是有

**Comment by XingXiaoWu** [comment]
建议给阿里提工单。
另外，旧App上架并不会被这个影响，新App才会

**Comment by as0026** [comment]
淘宝库的二进制文件包含有，自己解决不了，只能提供单让他们改。这该死的百川，果然不是亲儿子啊。

**Comment by jb522185660** [comment]
您好，请问这个问题解决了吗？不能上架的话没什么意义
