### ISSUE TITLE
调用 taokeLogin报错，找不到WebViewActivity这个类

### ISSUE THREAD

**Issue by zhj296409022** [FlutterTaoBaoKe/flutter_alibc#54]
PlatformException (PlatformException(error, Unable to find explicit activity class {com.yxwl.cbn_mobile/com.wxwx.flutter_alibc.web.WebViewActivity}; have you declared this activity in your AndroidManifest.xml?, null))

调用 taokeLogin的时候报这个错。。
不明白这个activity的路径是怎么生成的，为啥会这样？

**Comment by jb522185660** [comment]
具体是怎么解决这个问题的？

**Comment by zsirfs** [comment]
![image](https://user-images.githubusercontent.com/22249411/92322143-1a7bbe80-f062-11ea-9e3a-017134d74334.png)
这样子
