### ISSUE TITLE
在安卓10.0系统初始化出现闪退以下是错误日志，模拟器和真机都会您这边可以测试下

### ISSUE THREAD

**Issue by erzipl** [FlutterTaoBaoKe/flutter_alibc#57]
F/libc    ( 7638): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76a0b4f410 in tid 7982 (Thread-8), pid 7638 (liang.xiaoxiaochuan)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'HUAWEI/ELE-AL00/HWELE:10/HUAWEIELE-AL00/10.0.0.188C00:user/release-keys'
Revision: '0'
ABI: 'arm64'
SYSVMTYPE: Maple
APPVMTYPE: Art
Timestamp: 2020-05-21 12:44:10+0800
pid: 7638, tid: 7982, name: Thread-8  >>> com.jingjiang.liang.xiaoxiaochuan <<<
uid: 10167
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x76a0b4f410
Cause: execute-only (no-read) memory access error; likely due to data in .text.
    x0  000000000000000a  x1  0000000000000000  x2  00000076a0b4f410  x3  0000000000000002
    x4  00000000000000bd  x5  000000000000078c  x6  0000000000000000  x7  0000078c00000000
    x8  00000075e59a29bc  x9  00000075ff79d550  x10 00000075ff79d550  x11 00000075e990ccc0
    x12 00000075eb8e7c88  x13 0000000000000018  x14 0000000000000014  x15 00000000000000b3
    x16 000000772401f938  x17 0000007724013950  x18 00000075e59a22b8  x19 00000075ff74fcf0
    x20 00000075ff74fcf0  x21 000000760ef9f000  x22 0000000000000007  x23 0000000000000007
    x24 000000760ef9f000  x25 0000007694899438  x26 0000007632490340  x27 00000075ff79c8d0
    x28 0000007694899400  x29 00000075e5275880
    sp  00000075e5275780  lr  00000075e59a2488  pc  00000075e59a29cc
backtrace:
    NOTE: Function names and BuildId information is missing for some frames due
    NOTE: to unreadable libraries. For unwinds of apps, only shared libraries
    NOTE: found under the lib/ directory are readable.
      #00 pc 00000000000ca9cc  /data/data/com.jingjiang.liang.xiaoxiaochuan/app_SGLib/app_1590035696/main/libsgmainso-5.4.171.so

**Comment by woddp** [comment]
我也一样

**Comment by zhanghsgithub** [comment]
俺也一样

**Comment by zhanghsgithub** [comment]
我试了一下应该是和哪个插件有冲突，单独引用这个的话运行不会崩溃，但是一直没找到是和什么冲突

**Comment by zhanghsgithub** [comment]
targetSdkVersion 设置为30以下就没问题了。

**Comment by PigXiuYang** [comment]
我的安卓10.0系统 需要将 targetSdkVersion 设置为28才正常。29 还是闪退。

**Comment by karedem** [comment]
已更新版本 实测exmple设置为30 运行正常
