### ISSUE TITLE
安卓下，FlutterAlibc.taoKeLogin方法调用出错

### ISSUE THREAD

**Issue by jb522185660** [FlutterTaoBaoKe/flutter_alibc#59]
安卓下，FlutterAlibc.taoKeLogin方法调用出错

Exception has occurred.
PlatformException (PlatformException(error, Unable to find explicit activity class {com.example.commission/com.wxwx.flutter_alibc.web.WebViewActivity}; have you declared this activity in your AndroidManifest.xml?, null))

**Comment by zhj296409022** [comment]
AndroidManifest.xml 注册一下就好了

**Comment by zhj296409022** [comment]
AndroidManifest.xml里面加上

<activity android:name="com.wxwx.flutter_alibc.web.WebViewActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>

**Comment by zhj296409022** [comment]
AndroidManifest.xml里面注册这个activity就好了

`<activity android:name="com.wxwx.flutter_alibc.web.WebViewActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>`
