### ISSUE TITLE
IOS真机运行问题

### ISSUE THREAD

**Issue by mytxoo** [FlutterTaoBaoKe/flutter_alibc#60]
IOS真机运行无法通过openByUrl唤起淘宝客服端，请问需要是否少了那些配置？
只是加了source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git' 这一行，可以正常运行，但是点击商品没有反应，android的可以跳转

**Comment by XingXiaoWu** [comment]
建议用淘宝官方的demo跑一下看看效果是否一致

**Comment by XingXiaoWu** [comment]
有问题再打开
