### ISSUE TITLE
大佬可以适配一下1.17的吗

### ISSUE THREAD

**Issue by gap1994** [FlutterTaoBaoKe/flutter_alibc#61]
登录会有两次，第一次
![image](https://user-images.githubusercontent.com/9198081/82973077-1c68c700-a009-11ea-8f52-0ae8b48c520a.png)
登录，第二次
![image](https://user-images.githubusercontent.com/9198081/82973111-30142d80-a009-11ea-8e07-42c4958e49e5.png)
之后
![image](https://user-images.githubusercontent.com/9198081/82973185-56d26400-a009-11ea-81d6-360ac4cf6589.png)
切换前后台，就找不到activity

**Comment by karedem** [comment]
请尝试新版本 如有问题请重新打开此iss
