### ISSUE TITLE
百川版本更新下

### ISSUE THREAD

**Issue by erzipl** [FlutterTaoBaoKe/flutter_alibc#64]

**Comment by erzipl** [comment]
[!] CocoaPods could not find compatible versions for pod "AlibcTradeSDK":
      In Podfile:
        AlibcTradeSDK (= 4.0.1.6)

        flutter_alibc (from `.symlinks/plugins/flutter_alibc/ios`) was resolved to 0.0.1, which depends on
          AlibcTradeSDK (= 4.0.1.0)

**Comment by erzipl** [comment]
官方已经是4.0.1.6，但是alibc拉取的还是4.0.1.0

**Comment by XingXiaoWu** [comment]
你改一下依赖版本本地测试一下提个pr吧~
iOS现在就是改个标识的事
