### ISSUE TITLE
百川登陆提示loginService对象为空导致失败

### ISSUE THREAD

**Issue by jb522185660** [FlutterTaoBaoKe/flutter_alibc#66]
用flutter build apk --target-platform android-arm64命令打包以后，百川登陆FlutterAlibc.loginTaoBao()提示《loginService对象为空导致失败》，百川后台已经生成并下载安全图片，并且按照demo配置，但是直接真机调试debug模式又可以正常登陆，请问有没有什么思路可以解决？
key使用命令"keytool -genkey -v -keystore /Users/JackLi/Desktop/release.keystore -keyalg RSA -keysize 2048 -validity 10000 -alias release.keystore "生成的。
![image](https://user-images.githubusercontent.com/3723116/83844994-9bad7780-a73a-11ea-8540-c7f9eb193e83.png)

**Comment by jcleng** [comment]
这个提示有可能是因为初始化失败或者多次初始化(ios),如果是安卓话,有可能是`FlutterAlibcHandle.java`文件获取单例的时候`handle`
和`register`的数据不一致,可以尝试 2个都修改为 static

**Comment by karedem** [comment]
可以尝试下新的版本

**Comment by XingXiaoWu** [comment]
新版本没问题的话，我们就关闭了哦，有问题再打开
