### ISSUE TITLE
您好，上传到app store以后，因为UIWebView的问题被打回

### ISSUE THREAD

**Issue by jb522185660** [FlutterTaoBaoKe/flutter_alibc#67]
您好，上传到app store以后，因为UIWebView的问题被打回

ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

请问有什么解决方案吗？我这边提交过阿里百川的工单，他们那边说按照最新的来，不影响审核
![image](https://user-images.githubusercontent.com/3723116/84610567-8f20e000-aeed-11ea-872b-d46dfb9b3bc3.png)

**Comment by XingXiaoWu** [comment]
更新了
