### ISSUE TITLE
能不能帮忙出个教程

### ISSUE THREAD

**Issue by huangzhilin** [FlutterTaoBaoKe/flutter_alibc#68]
能不能帮忙出个教程，我集成这个都2个星期了，还是没有成功，目前网上没有找到相关的帮助，我是一名新手，希望能得到你们的帮助，谢谢！！

**Comment by fuiyu** [comment]
你遇到了什么问题咯，可以具体提提

**Comment by huangzhilin** [comment]
就是没有配置成功，也不知道怎么去配置

**Comment by huangzhilin** [comment]
今天是第3个星期了，还是没有配置成功，能不能出个简单的教程

**Comment by XingXiaoWu** [comment]
readme不是教程么- -
