### ISSUE TITLE
哥 上架ios市场一直提示ITMS-90809:已弃用的API用法-不再接受使用UIWebView的新应用程序

### ISSUE THREAD

**Issue by erzipl** [FlutterTaoBaoKe/flutter_alibc#69]
ITMS-90809:已弃用的API用法-不再接受使用UIWebView的新应用程序。相反，使用WKWebView来提高安全性和可靠性。了解更多(https://developer.apple.com/documentation/uikit/uiwebview).，已经查了只有百川的带这玩意，但是查到以后不知道该怎么做，有其他的用户这样子吗，麻烦能分享一下解决方法，已经提交了20次了

**Comment by XingXiaoWu** [comment]
不是更新了么？
新版听他们说没有uiwebview了啊
