### ISSUE TITLE
老铁  自定义webview可否考虑兼容下 

### ISSUE THREAD

**Issue by niugengyun** [FlutterTaoBaoKe/flutter_alibc#7]
使用场景：
套件场景: 淘宝联盟
套件ID: 3
套件描述: 淘宝客基础页面包

这样我们就可以根据页面拦截了

**Comment by XingXiaoWu** [comment]
等我研究一下

**Comment by niugengyun** [comment]
https://github.com/hetian9288/flutter_webview_plugin/  

可以参考这个 里面集成了百川

**Comment by XingXiaoWu** [comment]
好的，不过没这么快

**Comment by niugengyun** [comment]
坐等   仔细研究下这个项目 其实也不是那么难

**Comment by XingXiaoWu** [comment]
平时上班也没时间看这个

![111](https://user-images.githubusercontent.com/22769131/65390945-ca92e180-dd95-11e9-80b6-d725ffdafabc.jpg)

**Comment by XingXiaoWu** [comment]
他这个跑不起来，而且目前百川还是UIWebview，肯定要被淘汰，想等百川支持wkwebview了再搞

**Comment by XingXiaoWu** [comment]
你要的是不是渠道授权拿token？

**Comment by XingXiaoWu** [comment]
dev分支新增了一个叫taoKeLogin的方法，iOS可以直接拿access_token了，Android还在写 @niugengyun

**Comment by niugengyun** [comment]
> @niugengyun 你要的是不是渠道授权拿token？

授权获取pid哪一步知道吧，现在是用百川内置的webview打开的

我想要用我们自己自定义的webview打开，这样就能知道是否授权成功了

**Comment by XingXiaoWu** [comment]
我对百川的业务不了解，想从flutter插个webview进去我觉得没意义。不过可以把拦截登录拿到的所有参数抛给flutter

**Comment by niugengyun** [comment]
很有意义 ，
1、我们拦截不到地址
2、拦截不到服务端返回的授权结果
3、如果授权返回结果的网页时H5   点击H5里面的确定按钮 无法交互

**Comment by niugengyun** [comment]
可参考下同行返利APP的授权流程，目前我们的实现不了那样的效果

**Comment by XingXiaoWu** [comment]
1.我可以把拦截的url直接给flutter
2.同上
3.能交互
我指的不从flutter给webview，是指不从flutter给，我直接在原生给

**Comment by niugengyun** [comment]
授权不是分两步吗
第一步：使用百川免登陆
第二步：使用百川打开授权网址（这是百川内置的webview），我们无法知道服务端返回的信息，所以不知道授权是否成功

**Comment by XingXiaoWu** [comment]
我不太清楚你说的这个，可能是我们对一些东西定义的名词不一致导致的沟通差异。我描述一下以下步骤，你看是否满足你的场景。
1.调淘宝app，在淘宝app登录（没有app的降级h5登录）
2.集成方有个登录的url，需要通过openurl这个方式打开，我从原生给个自定义的webview，打开之后是个授权的h5，点击同意之后我直接把登录成功拦截到的url抛给flutter，你们就能拿到url了。
拦截这一步不由你们做，我来做
这个意思

**Comment by niugengyun** [comment]
是的  2就是
只要openURL能支持自定义webview就可以了

**Comment by XingXiaoWu** [comment]
那这个周末应该可以更新一版上去，到时候我关掉这个iss

**Comment by XingXiaoWu** [comment]
你需要哪个参数

**Comment by niugengyun** [comment]
只要可以传入自定义的webview就可以了，因为自定义webview可以取到网页的返回值，这样我就可以做处理了

**Comment by niugengyun** [comment]
https://github.com/FlutterTaoBaoKe/flutter_alibc/issues/27  
哥们 我看了 这个token是没用的，他只可以用来获取用户信息。
方便的话 留个联系方式 我直接微信给您说

**Comment by niugengyun** [comment]
@XingXiaoWu   哥们 来继续交流下

**Comment by niugengyun** [comment]
@XingXiaoWu   老哥

**Comment by XingXiaoWu** [comment]
抱歉最近加班较多，没时间看这个，等我周末看看，stream方式返给你，不过可能会反好几次

**Comment by XingXiaoWu** [comment]
> @XingXiaoWu 老哥

你可以先自己改动一下，返回什么的都写好了，你只要改一下你要的返回值截取key就能先用

**Comment by niugengyun** [comment]
> > @XingXiaoWu 老哥
> 
> 你可以先自己改动一下，返回什么的都写好了，你只要改一下你要的返回值截取key就能先用

不是 你处理的不对，我们不是用找哥哥额token取用户信息的，我们的目的是传入自定义webview，然后获取他浏览网页的地址

**Comment by XingXiaoWu** [comment]
> > > @XingXiaoWu 老哥
> > 
> > 
> > 你可以先自己改动一下，返回什么的都写好了，你只要改一下你要的返回值截取key就能先用
> 
> 不是 你处理的不对，我们不是用找哥哥额token取用户信息的，我们的目的是传入自定义webview，然后获取他浏览网页的地址

一样的，你把我的截取和关闭去了就行

**Comment by niugengyun** [comment]
https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.7629140.0.0.2384be48v5az6R&treeId=129&articleId=118399&docType=1

**Comment by XingXiaoWu** [comment]
> https://baichuan.taobao.com/docs/doc.htm?spm=a3c0d.7629140.0.0.2384be48v5az6R&treeId=129&articleId=118399&docType=1

发地址是啥意思

**Comment by niugengyun** [comment]
淘客app授权分两步：
第一步：阿里百川授权免登陆，
第二步：使用我们的openUrL打开授权页面（这里可传入自定义webview，我们可通过自定义webview知道他是否授权成功，因为信息是我们服务端返回的），现在不是自定义webview，我们取不到服务端返回的信息（网页内容）

**Comment by XingXiaoWu** [comment]
> 淘客app授权分两步：
> 第一步：阿里百川授权免登陆，
> 第二步：使用我们的openUrL打开授权页面（这里可传入自定义webview，我们可通过自定义webview知道他是否授权成功，因为信息是我们服务端返回的），现在不是自定义webview，我们取不到服务端返回的信息（网页内容）

现在就是自定义的webview，只是我拿了token就把webview关了而已。
你可以在原生代码中把这一段替换成返回url即可

**Comment by niugengyun** [comment]
具体使用场景，可查看粉象生活、高佣联盟这些app的授权逻辑，我提的这个不是我个人的需求，而是每个app都必须这样做。

因为内置webview取不到网页结果，这样我们授权后，需要刷新一下接口，才能在前端更新用户的状态

**Comment by XingXiaoWu** [comment]
> 具体使用场景，可查看粉象生活、高佣联盟这些app的授权逻辑，我提的这个不是我个人的需求，而是每个app都必须这样做。
> 
> 因为内置webview取不到网页结果，这样我们授权后，需要刷新一下接口，才能在前端更新用户的状态

没有啊。。。我现在就拿了token给后台绑了，绑完就完事了

**Comment by niugengyun** [comment]
我们这边不会IOS的flutter，建议可传入一个监听：1、兼容网页是否关闭  2、监听webview网页地址

**Comment by XingXiaoWu** [comment]
> 我们这边不会IOS的flutter，建议可传入一个监听：1、兼容网页是否关闭 2、监听webview网页地址

原生代码，跟flutter无关

**Comment by niugengyun** [comment]
我知道  我们没人会原生。

另外现在返回那个token也没啥用

**Comment by niugengyun** [comment]
加QQ聊

**Comment by niugengyun** [comment]
515343908

**Comment by gap1994** [comment]
@XingXiaoWu 大佬，这个token怎么获得的，我在taoKeLogin使用了
https://oauth.taobao.com/authorize?response_type=code&client_id=xxxxxxxx&redirect_uri=urn:ietf:wg:oauth:2.0:oob&state=1212&view=wap
这种链接，一直都是空白字符串，只有返回一个页面
