### ISSUE TITLE
判断淘宝和天猫app是否安装

### ISSUE THREAD

**Issue by as0026** [FlutterTaoBaoKe/flutter_alibc#70]
能否增加一个api，判断淘宝和天猫app在手机是否安装，因为在appStore审核的时候，测试官手机没有装淘宝app，然后打开一个“宝贝不见了”的网页，或者是下载淘宝app的网页，都是审核不通过的。
希望开发者加下哈

**Comment by XingXiaoWu** [comment]
你自己做个判断不就完了？

**Comment by as0026** [comment]
@XingXiaoWu 没有找到该判断的方法呢

**Comment by XingXiaoWu** [comment]
自己写啊

**Comment by as0026** [comment]
@XingXiaoWu ios不会写呢，只写dart应该搞不定吧

**Comment by XingXiaoWu** [comment]
这玩意我们也加不了，比如iOS，需要你在项目info.plist里加白名单。
这种功能都是自己写。

**Comment by Zhaimm** [comment]
使用url_launcher插件的canLaunch("taobao://")
