### ISSUE TITLE
 在淘宝APP返回导购APP按钮怎么加LOGO

### ISSUE THREAD

**Issue by chenhuaiyuan** [FlutterTaoBaoKe/flutter_alibc#71]
大神们，想问下这种返回小把手怎么加上导购APP的图标呢？现在是实现了有个返回按钮，但是不知道怎么加入导购APP的图标
![微信图片_20191105111328](https://user-images.githubusercontent.com/21691457/88199244-2d376100-cc77-11ea-8873-d0292d1bcf1b.jpg)

**Comment by nnianhou-** [comment]
leancloud统计功能

**Comment by dingdingillusion** [comment]
自己去找淘宝联盟的商务，满足一定流量之后可以申请开通

**Comment by karedem** [comment]
此功能不在插件涉及范围内~
