### ISSUE TITLE
关于FlutterAlibc.taoKeLogin授权问题

### ISSUE THREAD

**Issue by qieren** [FlutterTaoBaoKe/flutter_alibc#73]
你好：
     使用FlutterAlibc.taoKeLogin获取用户授权的accessToken，有个时候会停留在授权页面没有返回, 如图
<img width="213" alt="微信截图_20201008174930" src="https://user-images.githubusercontent.com/4198835/95443538-45be3a00-098f-11eb-992b-c00d921984aa.png">
    授权页面是参照demo里的https://oauth.taobao.com/authorize?response_type=token&client_id=********&state=1212&view=wap
     这个情况在ios里遇到, android暂时没发现(用的少)
     请问， 这种情况大概是什么原因？

**Comment by xfu008** [comment]
我也一样，安卓也没有返回

**Comment by XingXiaoWu** [comment]
看看输出里面有没有包含accessToken，如果没有的话，就不会返回。
至于为什么没有，得用百川的官方demo试一下看看是不是相同的情况；
如果百川官方demo也不会打印出accessToken，这个问题就需要找百川官方；
如果打印了没返回，我再来排查一下

**Comment by qieren** [comment]
https://oauth.taobao.com/authorize接口有一个参数是redirect_uri, 我的想法是通过这个参数的uri直接跳回自己的页面处理(用FlutterAlibc.openByUrl打开页面)
这里一个问题想请教, 如果是跳到一个自己的页面, 如何通过点击页面的按钮(或自动执行一个js 方法).来关闭这个窗口(返回app), 如果能同时返回参数就更好

**Comment by XingXiaoWu** [comment]
太久没有回复，暂时先关闭了，有问题再打开

**Comment by as0026** [comment]
请问楼上的解决了吗

**Comment by as0026** [comment]
用pc浏览器打开授权地址，点击授权之后也是这个图片，但是浏览器的地址为（https://oauth.taobao.com/oauth2?view=wap#access_token=610260215b18786f7ff71648e95814ccfdc122d5f8cdbdd1080818101&token_type=Bearer&expires_in=2592000&refresh_token=610040290611cfe4b8941027ee51a8dff8dd724db804c991080818101&re_expires_in=2592000&r1_expires_in=1800&r2_expires_in=0&taobao_open_uid=AAHjDFFEAKcxZ9JwdX15xp0L&taobao_user_id=1080818101&taobao_user_nick=hao_jiong8song&w1_expires_in=1800&w2_expires_in=0&state=1212&top_sign=8B4F6F0DC6EFAE8ACC98D1EF38057BAE），带有access_token。会不会是百川的sdk更新了，更换了新的方式？
求作者核实下咯
