### ISSUE TITLE
授权不返回和打不开url

### ISSUE THREAD

**Issue by lcm1475** [FlutterTaoBaoKe/flutter_alibc#74]
1.安卓的授权授权之后不自动跳回来 跳回来的时候accessToken也是空的 用的就是官方的demo
2.打开url的时候 显示宝贝不见了 但是这个链接直接浏览器访问是能打开的 用的也是官方的demo 没改动

**Comment by karedem** [comment]
已更新版本 如仍有问题请重新打开iss
