### ISSUE TITLE
FlutterAlibc.taoKeLogin

### ISSUE THREAD

**Issue by jessice-ai** [FlutterTaoBaoKe/flutter_alibc#76]
var result = await FlutterAlibc.taoKeLogin(
                    url:
                    "https://oauth.taobao.com/authorize?response_type=token&client_id=30174548&state=1212&view=wap",
                    openType: AlibcOpenType.AlibcOpenTypeNative,
                    isNeedCustomNativeFailMode: true,
                    nativeFailMode:
                    AlibcNativeFailMode.AlibcNativeFailModeJumpH5);
                print("---------------------------BBBBBBBBBBBBBBBBBBBBBBBBB---------------------- access Jessice token == ${result["accessToken"]}");

我打印出来的结果是:

I/flutter (13072): ---------------------------BBBBBBBBBBBBBBBBBBBBBBBBB---------------------- access Jessice token == 
D/AuthSDK_CredentialManager(13072): func isSessionValid
D/AuthSDK_CredentialManager(13072): time =2021-01-09 18:56:23 249
D/AuthSDK_CredentialManager(13072): isSessionValid()  true
D/AuthSDK_CredentialManager(13072): time =2021-01-09 18:56:23 252
D/CompatibilityChangeReporter(13072): Compat change id reported: 147798919; UID 10216; state: DISABLED
W/Choreographer(13072): Frame time is 0.333257 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.

没有获取到值呀

**Comment by jessice-ai** [comment]
点击授权按钮，调转过去是一个数字2的图标，不会自动调回来，怎么才能自动回来呢

**Comment by karedem** [comment]
已更新版本 还有问题的话请重新打开此iss
