### ISSUE TITLE
android sdk版本更新到4.0.0.26了，辛苦作者更新下吧

### ISSUE THREAD

**Issue by as0026** [FlutterTaoBaoKe/flutter_alibc#79]
阿里百川android sdk已经更新到4.0.0.26了，辛苦作者更新下吧，现在的用不了了。
http://baichuan-sdk.cn-hangzhou.oss-pub.aliyun-inc.com/19/android/4.0.0.26/%E7%99%BE%E5%B7%9Dsdk4.0.0.26.zip?spm=a3c0d.8115107.0.0&file=%E7%99%BE%E5%B7%9Dsdk4.0.0.26.zip

**Comment by XingXiaoWu** [comment]
@karedem

**Comment by Huzhengtao** [comment]
这从哪看到4.0.0.26的？百川官网都不维护了，sdk还显示最新4.0.0.8

**Comment by karedem** [comment]
4.0.0.16 已更新
