### ISSUE TITLE
openByUrl 函数  使用await无法正确等待结果  后面代码直接不执行

### ISSUE THREAD

**Issue by ismanong** [FlutterTaoBaoKe/flutter_alibc#8]
![image](https://user-images.githubusercontent.com/13862699/65385117-2ab96180-dd5d-11e9-98c8-8490f2ff1efa.png)
谢谢，还请测试下，【await FlutterAlibc.openByUrl】之后的代码，不会继续执行

**Comment by ismanong** [comment]
我可能表述不清晰，就是通过openByUrl打开一个淘客授权页面后，我手动关闭页面，或者通过js通讯webview关闭时， 这个await是一直挂起的，没有结果，所以不会执行后面代码。
我看了官方的代码，通过js桥接关闭webview是用activity.finish()来销毁页面的。
不知道是否可以增加关闭监听，并把结果返回出来，我对安卓很陌生，没法帮助贡献，抱歉

**Comment by karedem** [comment]
感谢您的反馈  我们也发现了这个问题  近期会尝试解决

**Comment by Slhaos7373** [comment]
希望能处理这个问题 谢谢

**Comment by karedem** [comment]
修复中~

**Comment by karedem** [comment]
我们发现如果有回调 是有返回的  比如加入购物车 或购买
await 阻塞的话  是因为没有回调返回的

我们新增了淘客授权接口  使用webview方式监听  关闭页面也会有返回  可以尝试用一下
