### ISSUE TITLE
pub依赖好像有问题啊

### ISSUE THREAD

**Issue by Huzhengtao** [FlutterTaoBaoKe/flutter_alibc#81]
直接运行example工程，安全初始化成功。flutter_alibc依赖的下载的源码。
更换成pub的dependencies，就安全初始化失败：errcode:1。这什么鬼啊。。。。
只是把本地相对路径依赖换成pub的就不行了？？？

**Comment by Huzhengtao** [comment]
依赖git可以。pub上的是很久没更新了吗，好像不能用了

**Comment by XingXiaoWu** [comment]
> 依赖git可以。pub上的是很久没更新了吗，好像不能用了

应该是可以的吧，不过我们更新了，有需要的话可以从 pub拉新版本
