### ISSUE TITLE
iOS 0.0.18 淘客授权 出错啦， xss chars included in params, such as <,>,',"".\

### ISSUE THREAD

**Issue by 1haoyu** [FlutterTaoBaoKe/flutter_alibc#82]
iOS 0.0.18 淘客授权 出错啦， xss chars included in params, such as <,>,',"".\

**Comment by Rainyun** [comment]
是因为您的请求参数中带有以下字符：<, >, ', "

**Comment by Rainyun** [comment]
> iOS 0.0.18 淘客授权 出错啦， xss chars included in params, such as <,>,',"".\

是因为您的请求参数中带有以下字符：<, >, ', "
