### ISSUE TITLE
支持null safety

### ISSUE THREAD

**Issue by windhc** [FlutterTaoBaoKe/flutter_alibc#83]

**Comment by GcNets** [comment]
加油哦

**Comment by windhc** [comment]
![image](https://user-images.githubusercontent.com/13448833/124549214-715c4b00-de61-11eb-9ce9-da50be38b4bf.png)

**Comment by XingXiaoWu** [comment]
改一下就行了么=。=

**Comment by windhc** [comment]
dart代码也要改，但需要改动的地方不多

**Comment by XingXiaoWu** [comment]
> dart代码也要改，但需要改动的地方不多
> 
> http://www.debuggerx.com/2021/03/07/migrate-flutter-project-to-null-safety/#%E6%9B%B4%E6%96%B0%E9%A1%B9%E7%9B%AE%E4%BB%A3%E7%A0%81

这个对我们而言有些困难了，我们都不是专职的flutter开发，你有兴趣提个pr么

**Comment by karedem** [comment]
> > dart代码也要改，但需要改动的地方不多
> > http://www.debuggerx.com/2021/03/07/migrate-flutter-project-to-null-safety/#%E6%9B%B4%E6%96%B0%E9%A1%B9%E7%9B%AE%E4%BB%A3%E7%A0%81
> 
> 这个对我们而言有些困难了，我们都不是专职的flutter开发，你有兴趣提个pr么

没事 月底前俺更新下

**Comment by karedem** [comment]
0.0.21-nullsafety 已更新
https://pub.dev/packages/flutter_alibc/versions
