### ISSUE TITLE
ios 无法还原包

### ISSUE THREAD

**Issue by GcNets** [FlutterTaoBaoKe/flutter_alibc#84]
[!] 'AliAuthSDK' uses the unencrypted 'http' protocol to transfer the Pod. Please be sure you're in a safe network with only trusted hosts. Otherwise, please reach out to the library author to notify them of this security issue.

注释 #use_frameworks!  后，

其他flutter 插件无法还原
例如fluwx

**Comment by huoda1237** [comment]
你好，你的注释以后可以解决问题吗？
