### ISSUE TITLE
debug可以，release不行

### ISSUE THREAD

**Issue by windhc** [FlutterTaoBaoKe/flutter_alibc#85]
flutter2.2

release编译的时候添加了 --no-shrink

debug时可以拉起淘宝，release之后无法拉起

**Comment by windhc** [comment]
flutter_alibc是0.0.18

**Comment by XingXiaoWu** [comment]
iOS？安卓？

**Comment by karedem** [comment]
可参考#38 
如仍有问题请重新打开iss
